# Series

In [4]:
import pandas as pd

series_test = pd.Series([100, 200, 300])
print(series_test)

0    100
1    200
2    300
dtype: int64

In [9]:
series_test2 = pd.Series({
    1996: 49,
    1997: 60,
    2019: 90,
})
series_test2

1996    49
1997    60
2019    90
dtype: int64

# DataFrames

In [21]:
frame_test = pd.DataFrame({
    1999: [10, 19,53],
    2000: [23, 54, 90],
    2001: [30, 88, 99 ]
})
frame_test

   1999  2000  2001
0    10    23    30
1    19    54    88
2    53    90    99

In [19]:
frame_test = pd.DataFrame([
    [10, 19,53],
    [23, 54, 90],
    [30, 88, 99 ]], columns=[2000,2001,2002])
frame_test

   2000  2001  2002
0    10    19    53
1    23    54    90
2    30    88    99

# Read Data

In [31]:
el_pais = pd.read_csv('./elpais_2019_02_28_articles.csv')

pd.options.display.max_rows = 10
el_pais

,body,title,uri
0,"\nÉl está en pareja, usted también. Se ven des...",Instrucción 16,https://elpais.com/elpais/2019/02/26/opinion/1...
1,"\nEn el interior de una casa de chapa, una muj...",La mujer que recibe las ‘visitas sorpresa’ de ...,https://elpais.com/internacional/2019/02/27/so...
2,\nUn gran fiasco. La cumbre de Hanói entre el ...,Corea del Norte y EE UU chocan sobre las razon...,https://elpais.com/internacional/2019/02/28/ac...
3,\nLa tregua pactada en Buenos Aires entre Dona...,Cohabitación incómoda,https://elpais.com/elpais/2019/02/24/opinion/1...
4,\n\n\n\nMÁS INFORMACIÓN\n\n\n\n\n\n\nXabier Ar...,"Muere Xabier Arzalluz, histórico dirigente del...",https://elpais.com/politica/2019/02/28/actuali...
...,...,...,...
70,\nEl Ejecutivo de Iván Duque ha situado en pue...,HRW denuncia que Colombia promueve a militares...,https://elpais.com/internacional/2019/02/27/co...
71,\n\n\n\n\nDirecto\n\n\nPrevia\n\n\n\n\nurlNoti...,"Valencia - Betis en directo, la Copa del Rey e...",https://elpais.com/deportes/2019/02/28/actuali...
72,\nWhat did audience members feel during the Ja...,The night when Lady Gaga performed in a baseme...,https://elpais.com/elpais/2019/02/27/inenglish...
73,\nLawyers representing the owner of the rural ...,Owner of land where Julen Roselló died will ar...,https://elpais.com/elpais/2019/02/28/inenglish...
74,"\nDwyane Wade, a los 37 años y en la recta fin...",Dwyane Wade vuelve a lo grande y tumba a los W...,https://elpais.com/deportes/2019/02/28/actuali...

# Index and selection

In [35]:
# Dictyonary like

el_pais['title']

0                                        Instrucción 16
1     La mujer que recibe las ‘visitas sorpresa’ de ...
2     Corea del Norte y EE UU chocan sobre las razon...
3                                 Cohabitación incómoda
4     Muere Xabier Arzalluz, histórico dirigente del...
                            ...
70    HRW denuncia que Colombia promueve a militares...
71    Valencia - Betis en directo, la Copa del Rey e...
72    The night when Lady Gaga performed in a baseme...
73    Owner of land where Julen Roselló died will ar...
74    Dwyane Wade vuelve a lo grande y tumba a los W...
Name: title, Length: 75, dtype: object

In [36]:
el_pais[['title', 'uri']]

,title,uri
0,Instrucción 16,https://elpais.com/elpais/2019/02/26/opinion/1...
1,La mujer que recibe las ‘visitas sorpresa’ de ...,https://elpais.com/internacional/2019/02/27/so...
2,Corea del Norte y EE UU chocan sobre las razon...,https://elpais.com/internacional/2019/02/28/ac...
3,Cohabitación incómoda,https://elpais.com/elpais/2019/02/24/opinion/1...
4,"Muere Xabier Arzalluz, histórico dirigente del...",https://elpais.com/politica/2019/02/28/actuali...
...,...,...
70,HRW denuncia que Colombia promueve a militares...,https://elpais.com/internacional/2019/02/27/co...
71,"Valencia - Betis en directo, la Copa del Rey e...",https://elpais.com/deportes/2019/02/28/actuali...
72,The night when Lady Gaga performed in a baseme...,https://elpais.com/elpais/2019/02/27/inenglish...
73,Owner of land where Julen Roselló died will ar...,https://elpais.com/elpais/2019/02/28/inenglish...
74,Dwyane Wade vuelve a lo grande y tumba a los W...,https://elpais.com/deportes/2019/02/28/actuali...

In [37]:
# Numpy like
el_pais.iloc[10:15]

,body,title,uri
10,"\nLa semana pasada, tras el empate sin goles c...",Un entrenador admirable,https://elpais.com/deportes/2019/02/28/actuali...
11,\n“Perú no es un país con una identidad. Tiene...,Vargas Llosa define Perú como el país de las m...,https://elpais.com/cultura/2019/02/27/actualid...
12,\n¡Blip! Suena la máquina y otro número aparec...,Trabajar los músculos es un seguro de vida (y ...,https://elpais.com/elpais/2019/02/18/buenavida...
13,\nLa economía de Estados Unidos se expandió en...,"La economía de Estados Unidos creció un 2,9% e...",https://elpais.com/economia/2019/02/28/actuali...
14,\nLa policía canadiense ha anunciado este miér...,Canadá incauta 180 kilos de metanfetamina esco...,https://elpais.com/internacional/2019/02/28/mu...

In [40]:
el_pais.iloc[12]['title']

'Trabajar los músculos es un seguro de vida (y las pesas no son necesarias)'

In [41]:
el_pais.iloc[:5, 0]

0    \nÉl está en pareja, usted también. Se ven des...
1    \nEn el interior de una casa de chapa, una muj...
2    \nUn gran fiasco. La cumbre de Hanói entre el ...
3    \nLa tregua pactada en Buenos Aires entre Dona...
4    \n\n\n\nMÁS INFORMACIÓN\n\n\n\n\n\n\nXabier Ar...
Name: body, dtype: object

In [43]:
el_pais.loc[:3, 'body':'title']

,body,title
0,"\nÉl está en pareja, usted también. Se ven des...",Instrucción 16
1,"\nEn el interior de una casa de chapa, una muj...",La mujer que recibe las ‘visitas sorpresa’ de ...
2,\nUn gran fiasco. La cumbre de Hanói entre el ...,Corea del Norte y EE UU chocan sobre las razon...
3,\nLa tregua pactada en Buenos Aires entre Dona...,Cohabitación incómoda

In [519]:
el_universal = pd.read_csv('./eluniversal_2019_02_28_articles.csv')
el_universal.loc[142:,'host':'uri']

,title,uri
142,"Reserva de datos en caso Martha Érika, ""una to...",http://www.eluniversal.com.mx/nacion/politica/...
143,"Exigen justicia para Laura Angélica, asesinada...",https://www.eluniversal.com.mx/estados/exigen-...
144,Tequisquiapan pierde fondos para seguridad,http://www.eluniversalqueretaro.mx/portada/teq...
145,SCT se reserva grabaciones del accidente aéreo...,https://www.eluniversal.com.mx/nacion/politica...
146,La UNAM celebra los 80 años de Batman,http://www.eluniversal.com.mx/espectaculos/cin...

In [490]:
el_universal.iloc[142]['title']

'Reserva de datos en caso Martha Érika, "una torpeza política total": De Mauleón'

# Data Wrangling

In [491]:
# 1. add newspeper_uid to the dataframe
el_universal['newspaper_uid'] = 'eluniversal'
el_universal

,body,title,uri,newspaper_uid
0,\n\nEl corporativismo en los sindicatos termin...,El cambio en materia laboral está en marcha: L...,http://www.eluniversal.com.mx/nacion/sindicato...,eluniversal
1,\nEl delito de violación fue otro de los delit...,Gobierno anterior también “maquillaba” cifras ...,http://www.eluniversal.com.mx/metropoli/cdmx/g...,eluniversal
2,El cantante Luis Miguel y su corista Mollie Go...,NaN,http://www.viveusa.mx/showbiz/luis-miguel-y-su...,eluniversal
3,\nARIES (21 marzo - 20 abril). \nTu impulso ha...,Tu horóscopo. Te adaptarás como pez en el agua,http://www.eluniversal.com.mx/espectaculos/far...,eluniversal
4,Seguramente has escuchado a más de una persona...,NaN,http://www.elbotiquin.mx/medicina-general/por-...,eluniversal
...,...,...,...,...
142,\nDurante el más reciente programa de “Con los...,"Reserva de datos en caso Martha Érika, ""una to...",http://www.eluniversal.com.mx/nacion/politica/...,eluniversal
143,"\nAguascalientes, Ags.- Estudiantes, docentes ...","Exigen justicia para Laura Angélica, asesinada...",https://www.eluniversal.com.mx/estados/exigen-...,eluniversal
144,El municipio de Tequisquiapan perdió los recur...,Tequisquiapan pierde fondos para seguridad,http://www.eluniversalqueretaro.mx/portada/teq...,eluniversal
145,\nRead in English\nLa Secretaría de Comunicaci...,SCT se reserva grabaciones del accidente aéreo...,https://www.eluniversal.com.mx/nacion/politica...,eluniversal
146,\nBatman está de manteles largos pues cumple 8...,La UNAM celebra los 80 años de Batman,http://www.eluniversal.com.mx/espectaculos/cin...,eluniversal

In [502]:
# 2. Getting the host
from urllib.parse import urlparse

el_universal['host'] = el_universal['uri'].apply(lambda uri: urlparse(uri).netloc)
el_universal

,body,title,uri,newspaper_uid,host
0,\n\nEl corporativismo en los sindicatos termin...,El cambio en materia laboral está en marcha: L...,http://www.eluniversal.com.mx/nacion/sindicato...,eluniversal,www.eluniversal.com.mx
1,\nEl delito de violación fue otro de los delit...,Gobierno anterior también “maquillaba” cifras ...,http://www.eluniversal.com.mx/metropoli/cdmx/g...,eluniversal,www.eluniversal.com.mx
2,El cantante Luis Miguel y su corista Mollie Go...,NaN,http://www.viveusa.mx/showbiz/luis-miguel-y-su...,eluniversal,www.viveusa.mx
3,\nARIES (21 marzo - 20 abril). \nTu impulso ha...,Tu horóscopo. Te adaptarás como pez en el agua,http://www.eluniversal.com.mx/espectaculos/far...,eluniversal,www.eluniversal.com.mx
4,Seguramente has escuchado a más de una persona...,NaN,http://www.elbotiquin.mx/medicina-general/por-...,eluniversal,www.elbotiquin.mx
...,...,...,...,...,...
142,\nDurante el más reciente programa de “Con los...,"Reserva de datos en caso Martha Érika, ""una to...",http://www.eluniversal.com.mx/nacion/politica/...,eluniversal,www.eluniversal.com.mx
143,"\nAguascalientes, Ags.- Estudiantes, docentes ...","Exigen justicia para Laura Angélica, asesinada...",https://www.eluniversal.com.mx/estados/exigen-...,eluniversal,www.eluniversal.com.mx
144,El municipio de Tequisquiapan perdió los recur...,Tequisquiapan pierde fondos para seguridad,http://www.eluniversalqueretaro.mx/portada/teq...,eluniversal,www.eluniversalqueretaro.mx
145,\nRead in English\nLa Secretaría de Comunicaci...,SCT se reserva grabaciones del accidente aéreo...,https://www.eluniversal.com.mx/nacion/politica...,eluniversal,www.eluniversal.com.mx
146,\nBatman está de manteles largos pues cumple 8...,La UNAM celebra los 80 años de Batman,http://www.eluniversal.com.mx/espectaculos/cin...,eluniversal,www.eluniversal.com.mx

In [504]:
el_universal['host'].value_counts()

www.eluniversal.com.mx         92
www.viveusa.mx                 10
www.elbotiquin.mx               9
oaxaca.eluniversal.com.mx       5
www.eluniversalqueretaro.mx     5
                               ..
www.unionyucatan.mx             3
www.unionpuebla.mx              2
www.unionedomex.mx              2
www.unionjalisco.mx             2
www.unioncdmx.mx                1
Name: host, Length: 14, dtype: int64